baseURL = "https://raise.systems/"
languageCode = "en-us"
title = "RAISE | Rapid AI Integration services"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true
PygmentsStyle = "manni"

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    logo = "images/logo.png"

    # Gestion des langues : FR / EN / NL / DE
    # [[Params.listeLangues]]
    # code = "fr"
    [[Params.listeLangues]]
    code = "en"
    [[Params.listeLangues]]
    code = "es"

# Gestion des langues : FR / EN / NL / DE
[Languages]
    ############ 1 - Site en FRANCAIS
    [Languages.fr]
    weight = 1
    languageCode = "fr-fr"
    title = "FRANCAIS Example site multi-language"
    dateFormat = "2 January 2006"

    home = "Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "FRANCAIS Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
    footerServiceTitle = "FRANCAIS Services"
    footerQuicklinkTitle = "FRANCAIS Quick links"
    footerAboutTitle = "FRANCAIS About"
    footerSubscribeTitle = "FRANCAIS Subscribe"

    # Hero Area Section
    [Languages.fr.params.hero]
        enable  = true
        heading = "FRANCAIS We love to make brands grow"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
        button  = true
        btnText = "Know More"
        btnURL  = "https://raise.systems/"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"
        heroBGURL   = "https://www.surveycto.com/wp-content/uploads/2018/04/ai-and-dev.jpg"

    # About 2 Section
    [Languages.fr.params.aboutSm]
        enable  = true
        title   = "FRANCAIS We have explored the digital landscape with passion for a long time"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

    # Blog Section On Homepage
    [Languages.fr.params.blog]
        enable  = true
        topTitle= "OUR UNTOLD STORY"
        title   = "FRANCAIS Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.fr.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "FRANCAIS Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        address = "14/05, Stockhome <br> Victori Palace , United States"
        phone   = "+34 633380251"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.fr.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "FRANCAIS Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Nous contacter"

    ############# 2 - Site en ENGLISH
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "Rapid AI Integration services"
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/logo.png"
    bgMP4 = "videos/aibg.mp4"
    # bgWEBM = "videos/aibg.webm"
    menufixed = false

    footerDescription = "We are passionate about Artificial Intelligence and boosting business performance. We've been working with Machine Learning and Big Data pipelines for years and we have provided several companies a competitive advantage."
    footerServiceTitle = "Service"
    footerQuicklinkTitle = "Quicklinks"
    footerAboutTitle = "About"
    footerSubscribeTitle = "Subscribe"

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "Rapid AI Integration services"
        description = "Leverage the latest technologies to give your company the leading edge in the era of Artificial Intelligence. We provide services to clients all over the world and across all types of industries."
        button  = false
        btnText = "Know More"
        btnURL  = "https://raise.systems/"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"
        heroBGURL   = "images/video-bg.jpg"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        title   = "We have the tools and expertise to grow any type of business"
        description = "Working for a wide spectrum of clients with different needs, from small projects to large scale Big Data deployments on clusters running on hundreds of nodes, we provide a competitive advantage by focusing on results and exploting existing technologies with the latest techniques in data integration and pipelines. We connect the machine learning and analysis systems with the data in no time."

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "Set up a meeting"
        title   = "Contact Us."
        subtitle= "The RAISE team is composed of highly skilled top-of-the-line engineers with experience in many different project sizes and we provide services to small, medium and large enterprises, giving our best on each project."
        address = "Valencia, Spain"
        phone   = "+34 633380251"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's work together"
        subtitle= "We are available for any size of project and we provide budgets free of charge, with predictable, accurate results.<br /> Don't hesitate to ask for a meeting with our experts to know what you can expect from our services."
        btnText = "Contact Us"

    ############# 2 - Site en ENGLISH
    [Languages.es]
    weight = 2
    languageCode = "es-es"
    title = "Integración rápida de tecnologías de Inteligencia Artificial"
    dateFormat = "2 January, 2006"

    home = "Inicio"
    logo = "images/logo.png"
    bgMP4 = "videos/aibg.mp4"
    # bgWEBM = "videos/aibg.webm"
    menufixed = false

    footerDescription = "Nos apasiona la Inteligencia Artificial y el aumento del rendimiento empresarial. Hemos estado trabajando con sistemas de Machine Learning y Big Data durante años y hemos proporcionado a varias empresas una ventaja competitiva."
    footerServiceTitle = "Servicio"
    footerQuicklinkTitle = "Enlaces"
    footerAboutTitle = "Equipo"
    footerSubscribeTitle = "Suscribirse"

    # Hero Area Section
    [Languages.es.params.hero]
        enable  = true
        heading = "Integración rápida de tecnologías de Inteligencia Artificial"
        description = "Ponemos a tu alcance las últimas tecnologías de AI para llevar a tu empresa a la vanguardia en la era de la Inteligencia Artificial. Brindamos servicios a clientes en todo el mundo y a todo tipo de industrias."
        button  = false
        btnText = "Know More"
        btnURL  = "https://raise.systems/"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"
        heroBGURL   = "images/video-bg.jpg"

    # About 2 Section
    [Languages.es.params.aboutSm]
        enable  = true
        title   = "Contamos con la experiencia y las herramientas para hacer crecer a cualquier tipo de empresa"
        description = "Trabajando para un amplio espectro de clientes con distintas necesidades, desde pequeños proyectos hasta implementaciones de Big Data a gran escala en clusters con cientos de nodos, brindamos una ventaja competitiva al concentrarnos en los resultados y explotar las tecnologías existentes con los últimos métodos en integración de datos y procesos. Conectamos los sistemas de Inteligencia Artificial y análisis con los datos en poco tiempo."

    # Blog Section On Homepage
    [Languages.es.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.es.params.contact]
        enable  = true
        topTitle= "Pide una entrevista"
        title   = "Contacto"
        subtitle= "El equipo de RAISE está compuesto por ingenieros del más alto nivel, altamente capacitados, con experiencia en todo tipo de proyectos, y brindamos servicios a pequeñas, medianas y grandes empresas, dando lo mejor de nosotros en cada proyecto."
        address = "Valencia, España"
        phone   = "+34 633380251"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.es.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Trabajemos juntos"
        subtitle= "Estamos disponibles para cualquier tamaño de proyecto y proporcionamos presupuestos sin cargo, con resultados predecibles y precisos. <br /> No dude en solicitar una reunión con nuestros expertos para saber qué puede esperar de nuestros servicios."
        btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "portfolio"
        url     = "portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "graphicdesign"
        url     = "service"
        weight  = 1
    [[menu.service]]
        name    = "webdesign"
        url     = "service"
        weight  = 2
    [[menu.service]]
        name    = "webdevelopment"
        url     = "service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "partners"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.quicklink]]
        name    = "faqs"
        url     = "about"
        weight  = 3
